l_simp_chinese:
 condan_hub_dig: "中央处理枢纽"
 condan_hub_dig_desc: "这个星球遭受了大规模的轨道轰炸，轨道上大量的太空残骸显示这里曾发生过一场大规模的舰队行动。\n\n对星球宏观结构的分析显示出一个中央设施的位置，这一结论也得到了星球该部分损毁程度远超其他地区的证实。"

 condan_arch.10.name: "防御网格"
 condan_arch.10.desc: "对该区域的详细勘测显示，这片星球表面几乎可以肯定是防御性质的。星球的地壳本身被改造成了一层复合装甲，厚度足以抵御除最大型舰载武器外的所有攻击。\n\n在初始装甲层以下，是一个由隧道和房间组成的蜂窝状结构，里面布满了自动防御系统，随后是第二层装甲和结构保护。一些系统仍然活跃，依靠内部电池维持运转，并且所有活跃的系统都试图攻击勘测队。\n\n若非针对该区域的集中轰炸，穿透这层防御几乎是不可能的。我们能够利用在装甲层上炸开的洞口进入下层区域，但寻找一条安全的下行路径仍需缓慢推进。好消息是，我们能够回收大量优质材料。"
 condan_arch.10.option.a: "小心推进"

 condan_arch.20.name: "通信枢纽"
 condan_arch.20.desc: "在装甲层下方，我们发现了通信中枢的遗迹。各种数据传输通道汇集于此，但大多数已经因轰炸而受损。\n\n尝试通过通信线路发送消息的实验表明，这些线路遍布整个星球，但受损严重。部分线路仍保持活跃，但我们无法翻译其数据内容。\n\n由于轨道轰炸的穿透破坏导致了大范围的损伤并引发了大量基础结构的坍塌，进展依然缓慢而困难。然而，勘测队确信这是星球的中央枢纽，通过追踪通信线路，我们可以找到星球核心的遗迹。"
 condan_arch.20.option.a: "继续前进"

 condan_arch.30.name: "星球核心"
 condan_arch.30.desc: "我们终于到达了星球的中央计算核心。核心舱室几乎完全坍塌，但我们成功访问了一个计算机系统。\n\n令人惊讶的是，这台计算机非常容易翻译，几乎像是在主动尝试与我们对接。\n\n$condan_arch.30.desc.list$"
 condan_arch.30.desc.1: "肃正枢纽1A6F智能状态：§R离线§!\n"
 condan_arch.30.desc.2: "星球休眠协议：§R失败§!\n"
 condan_arch.30.desc.2.1: "星球休眠协议调试：§R错误：§! \n--5% 休眠设备§G在线§! \n--20% 休眠设备§R错误§! \n--75% 休眠设备§R无信号§!\n"
 condan_arch.30.desc.3: "休眠决策监控子程序：§G活动§!\n"
 condan_arch.30.desc.4: "检测到生命形式。\n"
 condan_arch.30.desc.5: "技术水平：§P低下§!\n"
 condan_arch.30.desc.6: "创造 $condan_class_30$ 事件的可能性：§G极低§!\n"
 condan_arch.30.desc.7: "推测银河范围内的 $condan_class_30$ 事件概率：§G极低§!\n"
 condan_arch.30.desc.8: "中央枢纽信号：§R无§!\n"
 condan_arch.30.desc.8.1: "中央枢纽信号调试：\n--通信阵列：§R无信号§!\n"
 condan_arch.30.desc.9: "任务关键性：§G<5%§!\n"
 condan_arch.30.desc.10: "结论：§G激活主要智能。§! 启动肃正协议：§G非紧急状态。§!\n"
 condan_arch.30.desc.11: "§R错误：§! 无法自动激活主要控制。\n"
 condan_arch.30.desc.12: "§R重定向：§! 手动激活协议：§G可操作§!\n"
 condan_arch.30.desc.13: "手动覆盖指令如下：\n\n"
 condan_arch.30.desc.14: "指令相当简单，仅需重新连接一些数据和电源连接器。我们是否继续？"
 condan_arch.30.desc.list: "§L$condan_arch.30.desc.1$$condan_arch.30.desc.2$$condan_arch.30.desc.2.1$$condan_arch.30.desc.3$$condan_arch.30.desc.4$$condan_arch.30.desc.5$$condan_arch.30.desc.6$$condan_arch.30.desc.7$$condan_arch.30.desc.8$$condan_arch.30.desc.8.1$$condan_arch.30.desc.9$$condan_arch.30.desc.10$$condan_arch.30.desc.11$$condan_arch.30.desc.12$$condan_arch.30.desc.13$§!$condan_arch.30.desc.14$"

 condan_arch.30.option.a: "是，激活核心"
 condan_arch.30.option.b: "听起来是个糟糕的主意。摧毁它"
 condan_arch.30.option.b.tooltip: "我们摧毁核心，终结这一切，留下这个世界归我们所有"
 condan_arch.30.option.c: "唤醒一台思考机器？荒谬！摧毁一切"
