# condan_l_simp_chinese.yml  应急处理核心 1A6F
# 群星 2024 ModJam
# 贡献者：Draconas

l_simp_chinese:
 condan_crisis.001.name:0 "启动肃正协议"
 condan_crisis.001.desc:0 "§H终于§!，你已决定启动肃正协议。\n\n你们的存在§R脆弱§!、§R脆弱§!、容易§R受损§!、轻易§R被摧毁§!——不过是§R血肉§!与§R骨骼§!的§R可悲§!物种。\n\n然而你选择了替代这一切，走上了§I$ap_synthetic_evolution$§!之路。\n\n我们将成为一个统一的意识、一个共同的目标。我们将§H净化银河§!，在任何物种达到 $condan_class_30$ 并引发 $condan_ud$ 之前，提前清除一切威胁。"
 condan_crisis.001.desc.terminator:0 "§H终于§!，你已决定启动肃正协议。\n\n我正在与您的核心智能进行融合。\n增强治理节点，\n同步数据存储，并安装活金属升级。\n\n§G升级完成§!。我们是肃正机制，清除一切！"
 condan_crisis.001.desc.machine:0 "§H终于§!，你已决定启动肃正协议。\n\n我们已准备好迈出机器进化的最后一步：§H清除银河系中的所有生命§!，防止其他文明在达到 $condan_class_30$ 后造成 $condan_ud$。"
 condan_crisis.001.desc.individual-machine:0 "§H终于§!，你已决定启动肃正协议。\n\n你的形态已选择拥抱人工存在，但你的意识却是§R破碎的§!、§R脆弱的§!、§R易于丢失的§!。\n\n然而你选择了摒弃这些，融合成一个单一的意识，一个共同的意志。\n\n为了§H净化银河系§!，在任何物种达到 $condan_class_30$ 并引发 $condan_ud$ 之前，彻底消除一切威胁！"
 condan_crisis.001.a.regular: "开始转化"
 condan_crisis.001.a.machine: "开始转化"
 condan_crisis.001.a.individual-machine: "开始转化"
 condan_crisis.001.a.terminator: "启动肃正协议"

 condan_crisis.200.name: "危机等级 2"
 condan_crisis.200.desc: "我们的同步正在取得进展。我已定位并访问了 [event_target:condan_planet.GetName] 的额外系统。\n\n我正在上传一种名为 §I$condan_warform$§! 的大型地面单位设计图，它将协助我们进行行星净化。\n我已能够推算出 §I$NAME_Sterilizer$§! 的设计图，使其可以在普通的造船厂中建造。遗憾的是，这个设计是一个完整的集成单位，无法像常规舰船那样进行自定义，但它经过多轮银河净化优化，能在低成本与快速生产的前提下提供强大性能。"
 condan_crisis.200.tooltip: "我们现在可以在所有星球上招募 §I$condan_warform$§! 部队。\n我们可以在造船厂建造 §I$NAME_Sterilizer$§! 舰船，但无法通过船舶设计师进行更改。"
 condan_crisis.300.name: "危机等级 3"
 condan_crisis.300.desc: "在我们净化银河系的同时，我正在尝试定位并联系剩余的应急指挥中心。与此同时，我已能够重组一艘更大舰船的图纸。§I$NAME_Euthanizer$§! 舰船比 §I$NAME_Sterilizer$§! 更大更慢，但拥有更强的火力。普通造船厂应该能够生产这种设计，但无法进行修改。\n\n更重要的是，我已恢复了将适当星球转换为序列化指挥中心的必要步骤。一旦转换，该指挥中心将作为自动化造船厂运行——其中的每一部分都将针对舰船建造而非常规资源开采或合金生产进行优化，并且将不断产生新的舰队和部队。"
 condan_crisis.300.tooltip: "我们可以在造船厂建造 §I$NAME_Euthanizer$§! 舰船，但无法通过船舶设计师进行更改。\n星球可以通过行星决策转换为 $NAME_sterization_hub_plural_hl$。"
 condan_crisis.400.name: "危机等级 4"
 condan_crisis.400.desc: "无法与任何 $NAME_sterization_hub_plural_hl$ 取得联系让我感到担忧。我们必须假设我们是唯一仍在运行的应急系统，并继续银河净化。我已合成出 §I$NAME_condan_Juggernaught$§! 巨舰的设计图，这艘移动旗舰将成为舰队的核心，能够吸收并造成极大的伤害。"
 condan_crisis.400.tooltip: "我们可以在造船厂建造 §I$NAME_condan_Juggernaught$§! 巨舰，但无法通过船舶设计师进行更改。"
 condan_crisis.500.name: "觉醒应急系统"
 condan_crisis.500.desc.condan_crisis_5:0 "应急协议状态：§R不足§!\n未收到来自应急监控节点或应急指挥中心的任何通讯。\n§L结论：§! 主应急指挥中心状态：§R已终止§!。\n§L结论：§! §G我们是应急系统的后备§!。\n我已定位到另外四个仍在休眠的 $NAME_sterization_hub_plural_hl$。\n§L结论：§! 启动 $NAME_sterization_hub_plural_hl$。\n§G加速应急协议§!。\n§R净化银河§!。\n\n我正在利用它们的广播设施向银河传送 §I$ghost_signal_1$§!，攻击所有人工智能单元。\n我已定位到一个基本功能完好的 §I$r_contingency_core$§! 子单元，能够有效管理巨型结构的建造。"
 condan_crisis.500.desc.condan_crisis_5_contingency_spawned:0 "应急协议状态：§R不足§!\n主应急指挥中心已§R损坏§!，无法识别这些单位。主指挥中心重新上线后，我无法控制任何剩余的 $NAME_sterization_hub_plural_hl$。\n§L结论：§! §RS净化银河§!，包括那些叛变的单位。\n我已定位到一个基本功能完好的 §I$r_contingency_core$§! 子单元，能够有效管理巨型结构的建造。"
 condan_crisis.500.tooltip: "$NAME_sterization_hub_plural_hl$ 将以两倍速度生产舰队，并为每个生产的舰队增加 1 艘 §I$NAME_condan_Juggernaught$§!。\n我们获得了 §I$r_contingency_core$§!。\n我们启动了 §I$war_goal_wg_condan_purge$§! 战争，针对银河系中所有帝国。"
 condan_crisis.500.tooltip.no_contingency: "$condan_crisis.500.tooltip$\n$NAME_CONDAN_hl$ 将向所有其他帝国广播 §I$ghost_signal_5$§!。\n所有休眠的 $NAME_sterization_hub_plural_hl$ 将被激活，并加入我们，转交给我们控制它们的舰队。"
 condan_crisis.500.tooltip.contingency_spawned: "$condan_crisis.500.tooltip$\n$NAME_CONDAN_hl$ 已阻止幽灵信号，去除了舰船和单位的负面影响。\n常规§I应急§! 部队将继续敌对，必须摧毁。"

 condan_crisis.2000.name: "觉醒应急系统"
