l_simp_chinese:
 condan_synth.105.name: "更好的构建"
 condan_synth.105.desc: "机械身体的增强能力有很多，但我们可以更进一步，投入更多精力，构建一种更先进的形式"
 condan_synth.105.desc.individual-machine: "第一步是物理设计。我们目前的身体设计是为了个体操作，但在我们转变后，它们将仅仅是我们意识的无人机延伸。\n\n虽然我们有一个基础模板，但我们在升级外壳方面的经验意味着我们可以通过多种方式进行改进"
 condan_synth.105.adaptive: "添加 §I$trait_auto_mod_robotic$§!"
 condan_synth.105.adaptive.tt: "情境完成后，我们的物种将获得 §I$trait_auto_mod_robotic$§! 特征"
 condan_synth.105.rapid-assembly: "添加 §I$trait_robot_mass_produced$§!"
 condan_synth.105.rapid-assembly.tt: "情境完成后，我们的物种将获得 §I$trait_robot_mass_produced$§! 特征"
 condan_synth.105.none: "普通的无人机外壳就足够了"

 condan_synth.200.desc: "我们原以为完全数字化的心智益处是显而易见的，因此可以避免任何形式的反对。或许这是天真的。对完全合成化的反对非常强烈，必须立即处理。\n\n主要的批评集中在我们无法证明一个连续的自我能够安全地转移，并且在机器智能中继续“存在”"
 condan_synth.200.desc.individual-machine: "我们原以为将自己与一个单一的 §Y$machine_intelligence$§! 融合并防止宇宙毁灭将是显而易见的。或许这是天真的。对心理合并的反对非常强烈，必须立即处理。\n\n主要的批评集中在我们无法证明一个连续的自我将继续在机器智能中“存在”"

 condan_synth.205.desc.individual-machine: "将我们种群与机器智能合并的项目一直遭遇抵抗，导致激烈的示威活动，执法人员勉强控制住了局面。抗议者害怕失去那些赋予生命意义的东西。如果存在的意义是失去自我融入整体，那还有什么意义？\n\n抗议运动中的强硬派正在呼吁将某些城市指定为遗产保护区。这将允许反对者继续以独立个体的身份生活，脱离 $machine_intelligence$ 的联系"

 condan_synth.300.desc: "在我们的领土上，每个主要的城市中心，我们已经安装了合成化舱，准备接收我们的 [owner.species.GetName] 种群。他们的数字身份模式将合并，形成新的 §Y$machine_intelligence$§！\n\n这一天终于到来，我们将抛弃过去，拥抱作为肃正者的未来"
 condan_synth.300.desc.individual-machine: "在我们的领土上，每个主要的城市中心，我们已经安装了合成化舱，准备接收我们的 [owner.species.GetName] 种群。他们的数字身份模式将合并，形成新的 §Y$machine_intelligence$§！\n\n这一天终于到来，我们将抛弃过去，拥抱作为肃正者的未来"
 condan_synth.300.a: "拥抱未来"

 condan_synth.300.a.resistance.machine.tt: "将 §Y[Owner.GetNumSynthOpposition] [Owner.GetBiologicalPopOrPops]§! 转移到 §Y$d_condan_individualist_enclaves$§! 于 [root.owner.capital_scope.GetName]\n清除阻碍后返回 §Y[Owner.GetNumSynthOpposition] [Owner.GetMechanicalPopOrPops]§!\n\n合成化速度取决于情境方法和机器人组装建筑的数量。"
 condan_synth.300.a.resistance.tt: "将 §Y[Owner.GetNumSynthOpposition] [Owner.GetBiologicalPopOrPops]§! 转移到 §Y$d_biological_enclaves$§! 于 [root.owner.capital_scope.GetName]\n清除阻碍后返回 §Y[Owner.GetNumSynthOpposition] [Owner.GetMechanicalPopOrPops]§!\n\n合成化速度取决于情境方法和机器人组装建筑的数量。"
 condan_synth.300.a.heritage.tt: "将 §Y[Owner.GetNumSynthOpposition] [Owner.GetBiologicalPopOrPops]§! 转移到 §Y$d_old_towns$§! 于 [root.owner.capital_scope.GetName]\n清除阻碍后返回 §Y[Owner.GetNumSynthOpposition] [Owner.GetMechanicalPopOrPops]§!\n\n合成化速度取决于情境方法和机器人组装建筑的数量。"

 condan_synth.305.desc: "尽管 [root.owner.capital_scope.GetName] 上指定的遗产保护区已经获得了公众的好评，但这一举措或许太过成功。出于怀旧情结，大量游客涌向这些遗产地，开始压倒了那些拒绝成为机器智能一部分的居民。这些居民对于外来者的耐受性并不高。\n\n如果我们希望在这些地方保持真实感，可能需要限制旅游活动。另一方面，游客与居民之间的互动可能会提供有趣的社会学洞察。"

 condan_synth.310.a.tt: "§Y$situation_digitization$§! 情境进度速度为 §Y1§! 年： §G+25%§!\n\n§Y$synth_mass_demonstrations$§! 修正已从 [root.owner.capital_scope.GetName] 中移除\n\n"
 condan_synth.310.bad.murder:0 "够了，这种愚蠢的行为。§R终结这些异端！"
 condan_synth.310.bad.murder.tooltip:0 "所有 §I$ethic_spiritualist$§!, §I$ethic_xenophile$§! 和 §I$ethic_pacifist$§! 种群将被消灭。\n\n§Y$synth_mass_demonstrations$§! 修正已从 [root.owner.capital_scope.GetName] 中移除\n\n进化将迅速推进"

 condan_synth.400.name: "节点优先"
 condan_synth.400.desc: "我们的焦点转向新的集体意识，它将管理我们的文明。子功能将被委托给若干管理节点，我们应该优先考虑哪个？"
 condan_synth.400.cognitive: "$councilor_gestalt_cognitive$"
 condan_synth.400.cognitive.tt: "§I$councilor_gestalt_cognitive$§! 将获得 +3 级"
 condan_synth.400.growth: "$councilor_gestalt_growth$"
 condan_synth.400.growth.tt: "§I$councilor_gestalt_growth$§! 将获得 +3 级"
 condan_synth.400.legion: "$councilor_gestalt_legion$"
 condan_synth.400.legion.tt: "§I$councilor_gestalt_legion$§! 将获得 +3 级"
 condan_synth.400.regulatory: "$councilor_gestalt_regulatory$"
 condan_synth.400.regulatory.tt: "§I$councilor_gestalt_regulatory$§! 将获得 +3 级"

 condan_synth.4100.name: "升级"
 condan_synth.4100.desc: "将我们的智能升级为肃正者角色的过程相对简单。\n\n首先，我们的无人机外壳和内部系统将被增强以使用生物金属。\n接着，我们将专注于升级管理节点。\n最后，$NAME_CONDAN_hl$ 将合并我们的核心智能，完成这个过程。\n\n$NAME_CONDAN_hl$ 提供了大量关于 $sr_living_metal$ 的数据，这将加速过程"
 condan_synth.4100.servitor.desc: "将我们的智能升级为肃正者角色的过程相对简单。\n\n首先，我们的无人机外壳和内部系统将被增强以使用生物金属。\n§Y有机体§! 将被升级为新的无人机外壳。\n接着，我们将专注于升级管理节点。\n最后，$NAME_CONDAN_hl$ 将合并我们的核心智能，完成这个过程。\n\n$NAME_CONDAN_hl$ 提供了大量关于 $sr_living_metal$ 的数据，这将加速过程"

 condan_synth.4400.name: "节点优先"
 condan_synth.4400.desc: "升级过程将转向我们的管理节点。我们应该优先升级哪个节点？"
