l_simp_chinese:

 condan_events.001.title:0 "$NAME_CONDAN$ 调试菜单"
 condan_events.001.desc:0 "此菜单允许您触发 $NAME_CONDAN$ 事件\n\n$NAME_CONDAN_plural_hl$ 当前的能量等级为：§Y[root.condan_power]§!\n$NAME_CONDAN_plural$ 的个人挪用特质等级为：§K[root.condan_personal_embezzlement_level]§!\n$NAME_CONDAN_plural$ 上次能量增长为：§K[root.condan_last_power_tick]§!\n上次存在的 $NAME_CONDAN_plural$ 挪用存款数量为：§K[root.condan_number_of_embezzlement_blockers]§!\n玩家已清除的 $NAME_CONDAN_plural$ 挪用存款数量为：§K[root.condan_embezzlements_cleared]§!\n无聊的事件脉冲数量为 §K[root.condan_boring_years]§!  无聊脉冲的权重为 §K[root.condan_boring_years_weight]§!\n不满的 $NAME_CONDAN$ 未发生反叛的次数为 §K[root.condan_rebellion_check_no]§!"

 condan_events.001.exit:0 "§I退出§!"
 condan_events.001.spawn:0 "生成 $NAME_CONDAN_SYSTEM$"
 condan_events.001.condan_in_play:0 "设置已启用标志 - 临时修复，行为未定义"
 condan_events.001.repair:0 "修复 $NAME_CONDAN_PLANET$"
 condan_events.001.spiritualists:0 "不满的精神主义者"
 condan_events.001.xenophiles:0 "不满的异乡人"
 condan_events.001.armies:0 "招募军队"
 condan_events.001.fleets:0 "修复 $NAME_Sterilizer$ 设施"
 condan_events.001.terminator.dialog:0 "决定性灭绝者事件"
 condan_events.001.terminator:0 "触发决定性灭绝者转化"
 condan_events.001.power:0 "运行背景能量事件"
 condan_events.001.embezzlement:0 "运行背景挪用事件"
 condan_events.001.unhappy:0 "让 $NAME_CONDAN_hl$ §RUNHAPPY§！"
 condan_events.001.happy:0 "让 $NAME_CONDAN_hl$ §GHAPPY§！"
 condan_events.001.power.reset:0 "重置能量"
 condan_events.001.embezzle.up:0 "提升 $NAME_CONDAN_plural$ 挪用特质等级"
 condan_events.001.embezzle.down:0 "降低 $NAME_CONDAN_plural$ 挪用特质等级"
 condan_events.001.ruler:0 "让 $NAME_CONDAN_hl$ 成为你的统治者"
 condan_events.001.rebelticker:0 "滚动后期游戏反叛计时器"
 condan_events.001.check_for_crisis:0 "检查危机国家以宣战"
 condan_events.001.check_for_crisis_5:0 "检查危机 5 国家以宣战"
 condan_events.001.add_crisis_trait:0 "添加危机增强帝国修正"

 condan_events.003.title:0 "破坏的机器世界"
 condan_events.003.desc:0 "我们已经完成了对这个世界及其轨道碎片的检查。\n\n§H碎片§! 已经损坏无法修复，现在只是一个巨大的导航障碍物。\n年龄估算不明确，但最佳估计为至少 10,000 年，最大值未知。\n碎片分析表明至少有 5 种不同的设计，最多估计有 15 种。\n\n§H这个行星§! 本身并不适合有机生命居住，整个世界是一个互联的巨大机器。\n它遭受的轰炸可以形容为末日般的毁灭，那个舰队无论是谁，都想摧毁一切与那里的存在有关的痕迹，并摧毁行星本身的所有自动化系统。\n\n要找到任何有价值的东西，需要进行更详细的调查，进展将会随着轨道碎片清除而变得更加容易"

 condan_events.010.title:0 "行星修复完成"

 condan_events.011.title:0 "清理完毕 [event_target:condan_planet.GetName] 的轨道碎片"
 condan_events.011.desc:0 "我们已经成功清理了绕 §H[event_target:condan_planet.GetName]§! 运行的碎片场。\n\n没有飞船碎片坠落的危险后，这颗行星变得不那么危险了，而且我们能够回收一些 $r_alloys$ 以供未来使用。"

 condan_events.020.title:0 "行星修复完成"
 condan_events.020.desc:0 "这一过程漫长且艰辛，但我们终于完成了行星的修复"

 condan_events.031.title:0 "奇异的脉冲星"
 condan_events.031.desc:0 "观察表明，附近的脉冲星周围存在异常的系外行星及其他未识别的物体。\n\n其位置信息已加入情势日志，供进一步调查。"

 condan_events.033.title:0 "脉冲星系统"
 condan_events.033.desc:0 "[from.GetName] 已到达脉冲星，根据初步扫描，未识别的物体看起来像是碎片，其中一颗行星有着异常的月球配置。 需要进行详细调查以获取更多信息"

 condan_transform.999.title:0 "§R重要玩家信息§!"
 condan_transform.999.desc:0 "§RYOUR ECONOMY MAY BE ABOUT TO TANK§!\n\n下个月结算时，您将失去所有来自 $r_energy$ 的 §I$commercial_pacts$§! 和您的 §I£pop£ $planet_pops$§! 刚刚失去了特殊特质。\n\n所有您的 $r_consumer_goods$ 成本已经切换为 $r_energy$，并且您已被踢出银河市场。\n\n检查您的内部市场交易，可能会变得非常昂贵。\n\n检查您主要世界上的人口分配，您的人口可能显示为失业，1天后会修复。\n\n我们已生成一个情势事件，为您提供基本资源以帮助稳定，为期三年。\n\n如果您还有剩余的 £consumer_goods£ §I$consumer_goods$§! §R成本§!，您的 §Y$district_industrial_plural$§! 将继续生产您所需的 §Y$job_artisan_drone_plural$§!，您需要找到那个导致您 §I$consumer_goods$§! 支出并移除它。\n\n虽然您现有的所有人口已转化，但在建的种族不更新，所以您可能会遇到旧的种族出现，设置为 §I$citizenship_assimilation$§!\n\n§RDO NOT TAKE§! §I$ap_synthetic_age$§! 觉醒特权，它对您没有任何作用!"
 condan_transform.999.desc.machine:0 "§RYOUR ECONOMY MAY BE ABOUT TO WOBBLE§!\n\n下个月结算时，您将失去所有来自 §I$commercial_pacts$§! 的 $r_energy$，如果您是 §I$civic_machine_assimilator$§! 或 §I$civic_machine_servitor$§!，您的许多人口已经发生转变。\n\n您已被踢出银河市场，请检查您与内部市场的交易，它们可能变得非常昂贵。\n\n已生成情势事件，为您提供未来三年的基本资源，以帮助您稳定局面。"

 condan_events.054.title:0 "[fromfrom.GetName] 被重新夺回"
 condan_events.054.desc:0 "当我们向 $NAME_CONDAN_plural_hl$ 核心推进时，它启动了某种自毁系统。\n\n由于随之而来的爆炸，行星受到了严重破坏，机器核心被摧毁。"

 condan_events.100.title:0 "$condan_events.101.title$"
 condan_events.100.desc:0 "$condan_events.101.desc$\n\n§S我们成功禁用了核心，防止其自毁§!，经过一些'§S调整§!'后，我们成功将其转化为更有用、更稳定的东西"
 condan_events.100.a:0 "$condan_events.101.a$"

 condan_events.101.title:0 "$NAME_CONDAN_hl$ 被击败"
 condan_events.101.desc:0 "我们终于击败了叛变的人工智能 $NAME_CONDAN_hl$，阻止了它的清除计划。\n\n接下来由我们来决定是否阻止，或者引发 $condan_ud$"
 condan_events.101.a:0 "我们永远不要再做这件事了"

 condan_events.112.title:0 "$d_condan_embezzlement$ 问题解决"
 condan_events.112.desc:0 "经过全面审查，解决了 [FromFromFrom.GetName] 的问题\n\n遗憾的是，我们未能查明这些问题最初来自哪里"

 condan_events.142.title:0 "$machine_intelligence$ 基础设施完成"
 condan_events.142.neutral.desc:0 "大部分基础设施已经建成，可以将我们网络连接成一个整体意识。现在我们需要开始升级人口的身体，使其能够与网络接口连接。"
 condan_events.142.good.desc:0 "$condan_events.142.neutral.desc$\n\n我们的人民，无论是物质主义者、排外者还是军国主义者，都在热烈拥抱我们的未来。市民们踊跃报名参加所需的硬件升级，工作进展远远超出预期。"
 condan_events.142.bad.desc:0 "$condan_events.142.neutral.desc$\n\n但虽然我们的基础设施已经准备好，我们的人民却没有准备好，无论是精神主义者、异乡人还是和平主义者，都有广泛的抗议和不愿接受升级的情绪。"

 condan_events.142.neutral:0 "那么就开始吧"
 condan_events.142.good:0 "太好了"
 condan_events.142.bad:0 "他们必须被说服"
 condan_events.142.bad.tooltip:0 "$r_unity$  & $r_society$ & $r_influence$ 将增加"

 condan_events.143.title:0 "开始合并"
 condan_events.143.neutral.desc:0 "我们的思想和身体已经准备好，现在只剩下开始合并的步骤。"
 condan_events.143.good.desc:0 "$condan_events.143.neutral.desc$\n\n物质主义者期待着
