# condan_l_spanish.yml  Contingency Processing Core 1A6F
# Stellaris 2024 ModJam
# Contributors: Draconas

l_spanish:

 condan_events.001.title:0 "$NAME_CONDAN$ Debug Menu"
 condan_events.001.desc:0 "This menu lets you trigger $NAME_CONDAN$ events\n\n$NAME_CONDAN_plural_hl$ power level is: §Y[root.condan_power]§!\n$NAME_CONDAN_plural$ personal embezzlement trait level: §K[root.condan_personal_embezzlement_level]§!\n$NAME_CONDAN_plural$ power growth on last pulse: §K[root.condan_last_power_tick]§!\nNumber of $NAME_CONDAN_plural$ embezzlement deposits that existed on last tick: §K[root.condan_number_of_embezzlement_blockers]§!\nNumber of $NAME_CONDAN_plural$ embezzlement deposits player has cleared: §K[root.condan_embezzlements_cleared]§!\nNumber of boring flavour event pulses §K[root.condan_boring_years]§!.  Weight for a boring pulse §K[root.condan_boring_years_weight]§!\nNumber of times unhappy $NAME_CONDAN$ has not rebelled §K[root.condan_rebellion_check_no]§!"

 condan_events.001.exit:0 "§IExit§!"
 condan_events.001.spawn:0 "Spawn $NAME_CONDAN_SYSTEM$"
 condan_events.001.condan_in_play:0 "Set in play flag - temp fix only, behaviour undefined"
 condan_events.001.repair:0 "Repair $NAME_CONDAN_PLANET$"
 condan_events.001.spiritualists:0 "Unhappy spiritualists"
 condan_events.001.xenophiles:0 "Unhappy xenophiles"
 condan_events.001.armies:0 "Recruit armies"
 condan_events.001.fleets:0 "Repair $NAME_Sterilizer$ facility"
 condan_events.001.terminator.dialog:0 "Determined Exterminator Event"
 condan_events.001.terminator:0 "Finish DE Situation"
 condan_events.001.terminator.force:0 "Force Determined Exterminator (Regular)"
 condan_events.001.terminator.force.machine:0 "Force Determined Exterminator (Machine Intelligence)"
 condan_events.001.power:0 "Run the background power event"
 condan_events.001.embezzlement:0 "Run the background embezzlement event"
 condan_events.001.unhappy:0 "Make $NAME_CONDAN_hl$ §RUNHAPPY§!"
 condan_events.001.happy:0 "Make $NAME_CONDAN_hl$ §GHAPPY§!"
 condan_events.001.power.reset:0 "Reset power"
 condan_events.001.embezzle.up:0 "Raise $NAME_CONDAN_plural$ embezzle trait level"
 condan_events.001.embezzle.down:0 "Lower $NAME_CONDAN_plural$ embezzle trait level"
 condan_events.001.ruler:0 "Make $NAME_CONDAN_hl$ your ruler"
 condan_events.001.rebelticker:0 "Roll the late game rebellion ticker"
 condan_events.001.check_for_crisis:0 "Check for crisis countries to declare war on"
 condan_events.001.check_for_crisis_5:0 "Check for crisis 5 countries to declare war on"
 condan_events.001.add_crisis_trait:0 "Add Crisis boost Empire Modifier"


 condan_events.003.title:0 "Wrecked Machine World"
 condan_events.003.desc:0 "We have finished our examination of the world and the orbital debris.\n\n§HThe debris§! is all damaged beyond salvage, and is merely a massive navigation hazard now.\nAge estimates are inconclusive, but best estimates are put a minimum age of 10,000 years, maximum unknown.\nAnalysis of fragments indicates a minimum of 5 distinct designs, maximum estimated at 15.\n\n§HThe planet§! itself is not designed for organic habitation, the entire world was a single interconnected machine.\nThe bombardment it suffered is best described as apocalyptic, whoever those fleets were, they wanted to destroy every trace of whatever existed down there and destroy all automated systems of the planet itself.\n\nFinding anything of value will require more detailed investigation, and progress will be easier with the orbital debris cleared"

 condan_events.010.title:0 "Planet Repaired"

 condan_events.011.title:0 "Orbital Debris Cleared from [event_target:condan_planet.GetName]"
 condan_events.011.desc:0 "We have successfully cleaned up the debris fields that were orbiting §H[event_target:condan_planet.GetName]§!.\n\nThe planet is significantly less hazardous without chunks of spacecraft falling out of the sky and we were able to recycle an amount of $r_alloys$ for future use."

 condan_events.020.title:0 "Planet Repaired"
 condan_events.020.desc:0 "The process was long an laborious, but we have finished our repairs of the planet"

 condan_events.031.title:0 "Strange Pulsar"
 condan_events.031.desc:0 "Observations have shown anomalous exoplanets and other unidentified objects around a nearby pulsar.\n\nIts location has been added to the situation log for further investigation."

 condan_events.033.title:0 "Pulsar System"
 condan_events.033.desc:0 "[from.GetName] has arrived at the pulsar, from initial scans the unidentified objects look like debris, and one of the planets has an unusual moon configuration.  A detailed survey will be needed for more information"

 condan_transform.999.title:0 "§RIMPORTANT PLAYER INFORMATION§!"
 condan_transform.999.desc:0 "§RYOUR ECONOMY MAY BE ABOUT TO TANK§!\n\nOn the next month rollover you will lose all $r_energy$ from $r_trade_value$, §I$commercial_pacts$§! and your §I£pop£ $planet_pops$§! have just lost their special traits.\n\nAll your $r_consumer_goods$ costs have just switched over to $r_energy$ and you have been booted from the galactic market.\n\nCheck your trades against the internal market, they might have just become very expensive.\n\nCheck pop allocation on your major worlds.  Your pops may be showing as unemployed, that will fix in 1 day.\n\nA situation has been generated to give you basic resources for the next 3 years to help you stabilise.\n\nIf you have any remaining £consumer_goods£ §I$consumer_goods$§! §Rcosts§!, your §Y$district_industrial_plural$§! will continue to make §Y$job_artisan_drone_plural$§! you need to find the thing that is costing you §I$consumer_goods$§! and remove it.\n\nWhile all of your existing pops got converted, pops under construction don't update, so you may get some old species popping up, set them to §I$citizenship_assimilation$§!\n\n§RDO NOT TAKE§! §I$ap_synthetic_age$§! Ascension Perk, it will do nothing for you!"
 condan_transform.999.desc.machine:0 "§RYOUR ECONOMY MAY BE ABOUT TO WOBBLE§!\n\nOn the next month rollover you will lose all $r_energy$ from §I$commercial_pacts$§! and if you were a §I$civic_machine_assimilator$§! or §I$civic_machine_servitor$§! a whole bunch of your pops just got shifted.\n\nYou have been booted from the galactic market, check your trades against the internal market, they might have just become very expensive.\n\nA situation has been generated to give you basic resources for the next 3 years to help you stabilise."

 condan_events.054.title:0 "[fromfrom.GetName] recaptured"
 condan_events.054.desc:0 "As we pushed towards $NAME_CONDAN_plural_hl$ core, it activated some form of self destruct system.\n\nThe planet has been heavily damaged by the resulting explosions, and the machine core destroyed."

 condan_events.100.title:0 "$condan_events.101.title$"
 condan_events.100.desc:0 "$condan_events.101.desc$\n\n§SWe were able to disable the core before it could self-destruct§!, after some '§Sadjustments§!' it has been possible to repurpose it into something more useful, and less rebellious"
 condan_events.100.a:0 "$condan_events.101.a$"

 condan_events.101.title:0 "$NAME_CONDAN_hl$ Defeated"
 condan_events.101.desc:0 "We have finally defeated the rogue AI $NAME_CONDAN_hl$ before it could purge us all.\n\nIt's up to us now to prevent, or cause, $condan_ud$"
 condan_events.101.a:0 "Let's never do this again"

 condan_events.112.title:0 "$d_condan_embezzlement$ sorted"
 condan_events.112.desc:0 "A complete review has dealt with the issues on [FromFromFrom.GetName]\n\nUnfortunately we were unable to get to the bottom of where they had come from in the first place"

 condan_events.142.title:0 "$machine_intelligence$ Infrastructure completed"
 condan_events.142.neutral.desc:0 "The majority of the infrastructure is now in place to network ourselves into a single gestalt consciousness.  Now we need to begin the work of upgrading the bodies oof our population to interface with the network."
 condan_events.142.good.desc:0 "$condan_events.142.neutral.desc$\n\nOur people, be they materialists, xenophobes or militarists are embracing our future.  Citizens are reporting in droves for the required hardware upgrades, the work is proceeding well ahead of schedule."
 condan_events.142.bad.desc:0 "$condan_events.142.neutral.desc$\n\nBut while our infrastructure is ready, our people are not, be they spiritualists, xenophiles or pacifists there is widespread protest and reluctance to undergo the upgrade procedure."
 condan_events.142.neutral:0 "Let's get to it then"
 condan_events.142.good:0 "Excellent"
 condan_events.142.bad:0 "They will have to be convinced"
 condan_events.142.bad.tooltip:0 "$r_unity$  & $r_society$ & $r_influence$ costs for future states will increase"

 condan_events.143.title:0 "Commencing Merge"
 condan_events.143.neutral.desc:0 "Our minds and bodies are ready, all that remains is for us to begin the merge."
 condan_events.143.good.desc:0 "$condan_events.143.neutral.desc$\n\nMaterialists look forward to a new level of existence, xenophobes for the utter rejection of the concept of 'other' and militarists to the unbridled combat power from a million minds acting as one"
 condan_events.143.bad.desc:0 "$condan_events.143.neutral.desc$\n\nWidespread panic and civil unrest has broken out, especially among those that were 'force upgraded'. Millions of people are unready and unwilling to give up their individuality and the situation is deteriorating"
 condan_events.143.neutral:0 "Let's get to it then"
 condan_events.143.good:0 "Excellent"
 condan_events.143.bad.default:0 "Push through to the end"
 condan_events.143.bad.default.tooltip:0 "Costs will increase, and there will be widespread unrest."
 condan_events.143.bad.murder:0 "Enough of this foolishness.  §RTerminate the deviants§!"
 condan_events.143.bad.murder.tooltip:0 "All §I$ethic_spiritualist$§!, §I$ethic_xenophile$§!  and §I$ethic_pacifist$§! pops will be killed.  Evolution will advance rapidly"

 condan_events.201.title:0 "Begin automated production of a new fleet and armies"
